<a href="https://colab.research.google.com/github/masavi4401/python/blob/master/Copy_of_Copy_of_28_06_19.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Introduction to Object Oriented Programming (OOP) in Python

In [0]:
class classname:
  # some functions and variables
  # function -- used to perform the specific activity
  # variables -- Data(memory)

In [0]:
def test():
  print('Test() for function')
  return
test()

Test() for function


In [0]:
class demo:
  def test(self):
    print('test() for the class and method')
    return
obj=demo() #object creation
obj.test() #call for the method

test() for the class and method


In [0]:
class demo1:
  def fact(self,n):
    fact=1
    while(n!=0):
      fact=fact*n
      n=n-1
    return fact
p1=demo1()
print(p1.fact(5))

120


In [0]:
# Method
# def test(self,para1,para2)

In [0]:
class demo2:
  def __init__(self,p1,p2):
    self.p1=p1
    self.p2=p2
  def add(self,p1,p2):
    return p1 + p2
c1=demo2(10,20)
print(c1.add(100,200))

300


In [0]:
lst =[1,2,3,4]
print(lst)

[1, 2, 3, 4]


In [0]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array)

[1 2 3 4]


In [0]:
lst=[1,2,3,4]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
int64


In [0]:
lst=[1.0,2.5,3.6,9.5]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
float64


In [0]:
a1 = np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2 = np.array([(1,2),(3,4),(5,6)])
print(a2.shape)

(2, 3)
(3, 2)


In [0]:
#Re-shape the given array
#numpy.reshape(arrayname,reshape,order='C')
a1 = np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [0]:
#Append some data -- Horizontally
#hstack(array1,array2) -- will be automatically arranged in horizontal
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [0]:
#Append some data -- Vertical
#vstack(array1,array2) -- will be automatically arranged in vertically
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [0]:
#Generate random numbers from NP
a1=np.random.normal(5,0.5,10)
print(a1)

[5.17106054 4.73143935 4.90916771 4.46983327 4.54596601 5.01498003
 4.86573491 4.89923267 4.75908664 5.43501466]


In [0]:
# numpy.zeros() and numpy.one()
# Generate an array with all zeros -- numpy.zeros()
# numpy.zeros(shape, dtype = float, order="C")
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [0]:
np.zeros((2,2),dtype=np.int16)

array([[0, 0],
       [0, 0]], dtype=int16)

In [0]:
#np.ones(shape,dtype=float,order='C')
np.ones((4,3),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [0]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [0]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[2]=5
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [0]:
#arrange() -- particular
#numpy.arrange(start,end,step)
#start -- value
#end -- value
#step -- Gap between one value to another value
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [0]:
np.arange(2,20,2)
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [0]:
a1=np.array([(1,2,3),(4,5,6)])
print('First Row: ',a1[1])

First Row:  [4 5 6]


In [0]:
# Indexing and Slicing of Numpy
a1=np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [0]:
a1=np.array([(1,2,3),(4,5,6)])
print('Second Row: ',a1[1])

Second Row:  [4 5 6]


In [0]:
a1=np.array([(1,2,3),(4,5,6)])
print('Slicing Column: ',a1[:,1])

Slicing Column:  [2 5]


In [0]:
a1=np.array([(1,2,3),(4,5,6)])
print('Slicing Last Column: ',a1[:,2])

Slicing Last Column:  [3 6]


In [0]:
a1=np.array([(1,2,3),(4,5,6)])
print('Row and Column',a1[1,:1])

Row and Column [4]


In [0]:
# Some math Operation on given random numbers
# Min    -- returns the least number
# Max    -- returns the large number
# Mean   -- Mean
# Median -- Medium
a1=np.random.normal(5,1,10)
print(a1)
print('Min value =',np.min(a1))
print('Max value =',np.max(a1))
print('Mean value =',np.mean(a1))
print('Median value =',np.median(a1))

[6.17306332 4.86454457 4.794547   3.36199818 6.40967938 5.47253827
 4.64398896 6.10899099 5.53632477 4.91628981]
Min value = 3.361998175019009
Max value = 6.409679377222382
Mean value = 5.228196523456606
Median value = 5.194414037807153


In [0]:
# Multiplication of 1D arrays
# numpy.dot(x,y) --
c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)

14

In [0]:
c1=np.array([(1,2),(3,4)])
c2=np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

In [0]:
b1=np.array([(1,5),(6,9)])
b2=np.array([(1,3),(1,6)])
np.matmul(b1,b2)

array([[ 6, 33],
       [15, 72]])

###Pandas Basics

In [1]:
import pandas as pd
dict={'Name':['masavi','hethvi'],'EmailID':['masavi@gmail.com','hethvi@gmail.com'],'MobileNumber':['84854','65956'],'Address':
     ['Hyd','Hyd']}
b=pd.DataFrame(dict)
print(b)

     Name           EmailID MobileNumber Address
0  masavi  masavi@gmail.com        84854     Hyd
1  hethvi  hethvi@gmail.com        65956     Hyd


In [2]:
b.index=['01','02']
print(b)

      Name           EmailID MobileNumber Address
01  masavi  masavi@gmail.com        84854     Hyd
02  hethvi  hethvi@gmail.com        65956     Hyd


In [0]:
# supermarket.csv -- Analysis (Which product having higher % of selling)
# Which products having least selling %
import pandas as pd
products=pd.read_csv('FileName.csv')
print(products)

In [0]:
import pandas as pd
product_sellingdata=pd.read_csv('FileName.csv',index_col=1)
print(product_sellingdata)